name: 'Web Platform Baseline Analyzer'
description: '🔍 Automatically catch browser compatibility issues in pull requests using real-time Web Platform Status API data'
author: 'Atharva Kanherkar'

branding:
  icon: 'search'
  color: 'orange'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  
  target-browsers:
    description: 'Target browser versions (comma-separated)'
    required: false
    default: 'chrome >= 90, firefox >= 88, safari >= 14, edge >= 90'
  
  blocking-level:
    description: 'Action behavior: none (comments only), warning (recommended), error (block high risk), critical (block critical only)'
    required: false
    default: 'warning'
  
  large-pr-threshold:
    description: 'Number of files that constitute a large PR'
    required: false
    default: '20'
  
  huge-pr-threshold:
    description: 'The number of files changed to consider a PR "huge".'
    required: false
    default: 50
  
  risk-level-filter:
    description: 'Filter results by risk level. Options: `low`, `medium`, `high`, `critical`.'
    required: false
    default: 'medium'
  
  enable-ai-review:
    description: 'Enable AI-powered review suggestions with Perplexity'
    required: false
    default: 'false'
  
  perplexity-api-key:
    description: 'Perplexity API key for AI-powered suggestions (optional)'
    required: false
  
  openai-api-key:
    description: 'OpenAI API key for AI features (deprecated - use perplexity-api-key)'
    required: false

outputs:
  should-block:
    description: 'Whether the PR should be blocked'
  
  risk-count:
    description: 'Number of compatibility risks found'
  
  decision:
    description: 'Final analysis decision'

runs:
  using: 'node20'
  main: 'dist/bundled/index.js'
