name: Baseline Compatibility Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  baseline-check:
    name: Check Baseline Compatibility
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build Analyzer
        run: npm run build
      
      - name: Run Baseline Analysis
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target-browsers: |
            chrome >= 90
            firefox >= 88
            safari >= 14
            edge >= 90
          blocking-level: 'HIGH'
          large-pr-threshold: 20
          huge-pr-threshold: 50
          enable-ai-review: false
